### ISSUE TITLE
AppImage fails to run on latest Raspbian Bullseye

### ISSUE THREAD

**Issue by xird** [koendv/arduino-ide-raspberrypi#4]
I've just done a clean install of the latest Raspberry Pi OS Bullseye on a Raspberry Pi 4. I then downloaded (to external HD as suggested) the latest AppImage from the releases page, did chmod +x and tried to run it. This results in "No such file or directory" error. 

Running `file` on the AppImage says `interpreter /lib/ld-linux-aarch64.so.1`. No such file is present in `/lib`.

Am I missing some dependency?

**Comment by xird** [comment]
Nevermind, I was running a 32-bit version of Raspberry Pi OS. Works as expected after switching to 64-bit.

**Comment by koendv** [comment]
Glad to hear it, I was getting worried.
best,
koen
