### ISSUE TITLE
Difficulty Installing AppImage on Raspbian 11

### ISSUE THREAD

**Issue by nanotrav** [koendv/arduino-ide-raspberrypi#5]
Hello, I am running a Raspbian 11 on a Raspberry Pi 4B and have not been able to install the ARM ports you've made here.

I am attempting to install on an external USB disk. I made the AppImage file executable, but nothing seems to happen after choosing to run the executable, in terminal or otherwise. I have attempted to install the three latest versions you've released, all with the same results. While I am not on Ubuntu, I did install fuse and libfuse2, but it did not make any difference. Navigating to the file through terminal returns that there is no such file or directory.

**Comment by koendv** [comment]
On a clean install of Raspberry Pi OS on a Raspberry Pi 4B, I was able to run the arduino ide. I first had to install
```
sudo apt-get install fuse libfuse-dev
```
![20240210_15h08m49s_grim](https://github.com/koendv/arduino-ide-raspberrypi/assets/2753612/d2584a97-9000-4e2d-a31b-71c1d9bceba1)
